permalink: /blog/:year/:month/:day/:title

github_url: https://github.com/partidodigital
planilla_gastos_id: 1ECohuUeBik_2rxvppS3sBHqm_gXpuNbOOYqRoMGans0
tagmanager: GTM-WPDQFCR
ga: UA-64073239-3

excerpt_separator: "<!--more-->"

timezone: America/Montevideo
markdown: kramdown
collections_dir: collections
plugins:
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-sitemap

css_dir: "/assets/style/"

# jekyll-seo-tag configuration
author: "Leo Giovanetti"
url: 
title: "Partido Digital de Uruguay"
description: "Somos un partido político que trabaja por un Uruguay moderno, innovador y participativo. Queremos que tu opinión sea tenida en cuenta todos los días, no solo cuando vienen las elecciones. ¿Te sumás?"
twitter:
  username: "pdigitaluy"
logo: "https://recursos.partidodigital.org.uy/assets/img/presentacion.jpg"

collections:
  documentos:
    output: true
  paginas:
    output: true
    permalink: /:path/

exclude_prose:
  - _paginas/blog.md
  - _paginas/documentacion.md
  - _paginas/formularios/encuesta-satisfaccion.md

defaults:
  - scope:
      path: ""
      type: documentos
    values:
      layout: pagina
  - scope:
      path: ""
      type: paginas
    values:
      layout: pagina
  - scope:
      path: ""
      type: posts
    values:
      layout: post

algolia:
  application_id: 9SWKMC2I4H
  index_name: jekyll
  settings:                                                                      
    attributeForDistinct: collection 

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - .gitignore
