permalink: /blog/:categories/:year/:month/:day/:title
github_url: https://github.com/partidodigital
excerpt_separator: "<!--more-->"

timezone: America/Montevideo
markdown: kramdown
collections_dir: collections
plugins:
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-sitemap

css_dir: "/assets/style/"

# jekyll-seo-tag configuration
author: "Leo Giovanetti"
url: https://partidodigital.github.io/PartidoDigital-Web-Next
title: "Partido Digital de Uruguay"
description: "Somos un partido político que trabaja por un Uruguay moderno, innovador y participativo. Queremos que tu opinión sea tenida en cuenta todos los días, no solo cuando vienen las elecciones. ¿Te sumás?"
twitter:
  username: "pdigitaluy"
logo: "https://recursos.partidodigital.org.uy/assets/img/presentacion.jpg"

collections:
  documentos:
    output: true
  paginas:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: documentos
    values:
      layout: pagina
  - scope:
      path: ""
      type: paginas
    values:
      layout: pagina
  - scope:
      path: ""
      type: posts
    values:
      layout: post

algolia:
  application_id: 9SWKMC2I4H
  index_name: jekyll
  settings:                                                                      
    attributeForDistinct: collection 

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - .gitignore