url: https://partidodigital.github.io/PartidoDigital-Web-Next
permalink: /blog/:categories/:year/:month/:day/:title
github_url: https://github.com/partidodigital
excerpt_separator: "<!--more-->"

timezone: America/Montevideo
markdown: kramdown
collections_dir: _collections
plugins:
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-sitemap

collections:
  documentos:
    output: true
  paginas:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: documentos
    values:
      layout: pagina
  - scope:
      path: ""
      type: paginas
    values:
      layout: pagina
  - scope:
      path: ""
      type: posts
    values:
      layout: post

algolia:
  application_id: 9SWKMC2I4H
  index_name: jekyll

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - .gitignore