url: https://partidodigital.github.io/PartidoDigital-Web-Next
permalink: /blog/:categories/:year/:month/:day/:title
excerpt_separator: "<!--more-->"

timezone: America/Montevideo
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-postcss
  - jekyll-sitemap

collections:
  documentos:
    output: true

defaults:
  - scope:
      path: ""
      type: documentos
    values:
      layout: page

typescript:
  tsc: "npx tsc"
  js_dest: "assets/scripts"

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - .gitignore