name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-18.04
    steps:
      - name: 📂 setup repo
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - name: 💎 setup ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: 2.7.2
      - name: ⬡ setup node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
      - name: 🔨⬡ install node dependencies
        run: npm install
      - name: 🔨💎 install ruby dependencies & build site
        uses: limjh16/jekyll-action-ts@v2
        env:
          NODE_ENV: production
          JEKYLL_ENV: production
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        with:
          enable_cache: false
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site
